#!/usr/bin/env python
import os
import shutil
import sys
import tempfile

import stage1
import stage2

from common import *
import yumconf


def check_running_as_root():
    if os.getuid() != 0:
        errormsg("Error: You need to be root to run this script")
        return False
    return True


def make_tarball(basearch, dver, metapackage, patch_dirs, prog_dir, stage_dir, relnum="0"):
    """Run all the steps to make a non-root tarball.
    Returns (success (bool), tarball_path (relative), tarball_size (in bytes))

    """
    yum = yumconf.YumConfig(dver, basearch)
    try:
        version = yum.query_osg_version()
        tarball_path = "%(metapackage)s-%(version)s-%(relnum)s.%(dver)s.%(basearch)s.tar.gz" % locals()

        post_scripts_dir = os.path.join(prog_dir, "post-install")

        statusmsg("Making stage 2 tarball for %s" % (metapackage))
        if not stage2.make_stage2_tarball(
                stage_dir        = stage_dir,
                packages         = ['osg-ca-scripts', metapackage],
                tarball          = tarball_path,
                patch_dirs       = patch_dirs,
                post_scripts_dir = post_scripts_dir,
                dver             = dver,
                basearch         = basearch,
                relnum           = relnum):
            errormsg("Making stage 2 tarball for %s unsuccessful. Files have been left in %r" % (metapackage, stage_dir))
            return (False, None, 0)
        tarball_size = os.stat(tarball_path)[6]
        return (True, tarball_path, tarball_size)
    finally:
        del yum


def print_usage(prog_name):
    print("Usage: %s <release-number> %s %s" % (prog_name,
                                  "|".join(VALID_DVERS),
                                  "|".join(VALID_BASEARCHES)))
    print "   or: %s <release-number> all" % prog_name


def main(argv):
    prog_name = os.path.basename(argv[0])
    prog_dir = os.path.dirname(argv[0])

    if len(argv) < 3 or (len(argv) == 3 and "all" != argv[2]) or len(argv) > 4:
        print_usage(prog_name)
        return 2

    relnum = argv[1]
    if not relnum:
        print "release-number not specified!"
        print_usage(prog_name)
        return 2

    statusmsg("Checking privileges")
    if not check_running_as_root():
        return 1

    if "all" == argv[2]:
        dvers        = VALID_DVERS
        basearches   = VALID_BASEARCHES
    else:
        if argv[2] in VALID_DVERS:
            dvers = [argv[2]]
        else:
            print("Invalid dver %r, should be one of %r" % (argv[2], VALID_DVERS))
            return 2
        if argv[3] in VALID_BASEARCHES:
            basearches = [argv[3]]
        else:
            print("Invalid basearch %r, should be one of %r" % (argv[3], VALID_BASEARCHES))
            return 2

    failed_paramsets = []
    written_tarballs = []
    for dver in dvers:
        for basearch in basearches:

            def _make_tarball_with_paramset(metapackage, patch_dirs, stage_dir):
                (success, tarball_path, tarball_size) = \
                    make_tarball(
                        basearch=basearch,
                        dver=dver,
                        metapackage=metapackage,
                        patch_dirs=patch_dirs,
                        prog_dir=prog_dir,
                        stage_dir=stage_dir,
                        relnum=relnum)

                if success:
                    written_tarballs.append([tarball_path, tarball_size])
                    print "Tarball created as %r, size %d bytes" % (tarball_path, tarball_size)
                    return True
                else:
                    failed_paramsets.append([dver, basearch])
                    return False
            #end _make_tarball_with_paramset

            stage_dir_parent = tempfile.mkdtemp(prefix='stagedir-%s-%s-' % (dver, basearch))
            wn_stage_dir = os.path.join(stage_dir_parent, 'osg-wn-client')
            full_stage_dir = os.path.join(stage_dir_parent, 'osg-client')

            statusmsg("Making stage 1 dir")
            if not stage1.make_stage1_dir(wn_stage_dir, dver, basearch):
                errormsg("Making stage 1 dir unsuccessful. Files have been left in %r" % wn_stage_dir)
                failed_paramsets.append([dver, basearch])
                continue

            if not _make_tarball_with_paramset('osg-wn-client', os.path.join(prog_dir, "patches/wn-client"), wn_stage_dir):
                continue

            shutil.move(wn_stage_dir, full_stage_dir)
            if not _make_tarball_with_paramset('osg-client', os.path.join(prog_dir, "patches/full-client"), full_stage_dir):
                continue

            statusmsg("Removing temp dirs")
            shutil.rmtree(stage_dir_parent, ignore_errors=True)
        #end for basearch in basearches
    #end for dver in dvers

    if written_tarballs:
        statusmsg("The following tarballs were written:")
        for tarball in written_tarballs:
            print "    path: %-50s size: %9d bytes" % (tarball[0], tarball[1])
    if failed_paramsets:
        errormsg("The following sets of parameters failed:")
        for paramset in failed_paramsets:
            print "    dver: %3s buildarch: %-6s" % (paramset[0], paramset[1])
        return 1

    return 0

if __name__ == "__main__":
    sys.exit(main(sys.argv))

