#!/bin/sh
if command -v python >/dev/null 2>&1; then
    python=python
elif command -v python3 >/dev/null 2>&1; then
    python=python3
elif command -v python2 >/dev/null 2>&1; then
    python=python2
elif test -x /usr/libexec/platform-python; then
    python=/usr/libexec/platform-python
else
    echo >&2 "Can't find Python"
    exit 127
fi

exec "$python" "$(dirname "$0")/make_client_tarball.py" "$@"
