#!/usr/bin/env python
import glob
import re
import os
import shutil
import subprocess
import sys
import tempfile

import stage1
import stage2


def main(argv):
    if len(argv) != 4:
        print "Usage: %s <metapackage> el5|el6 i386|x86_64" % os.path.basename(argv[0])
        return 2
        # TODO more (user) instructions here

    metapackage = argv[1]
    dver = argv[2]
    basearch = argv[3]

    stage_dir_parent = tempfile.mkdtemp()
    stage_dir = os.path.join(stage_dir_parent, metapackage)

    print "Making stage 1 dir"
    if not stage1.make_stage1_dir(stage_dir, dver, basearch):
        return 1

    tarball = "%s-%s-%s-nonroot.tar.gz" % (metapackage, dver, basearch)
    # FIXME only works if metapackage is osg-wn-client or osg-client
    patch_dirs = [os.path.join(os.path.dirname(argv[0]), "patches/wn-client")]
    if "osg-client" == metapackage:
        patch_dirs.append(os.path.join(os.path.dirname(argv[0]), "patches/full-client"))
    scripts_dir = os.path.join(os.path.dirname(argv[0]), "post-install")

    print "Making stage 2 tarball"
    if not stage2.make_stage2_tarball(stage_dir, ['osg-ca-scripts', metapackage], tarball, patch_dirs, scripts_dir, dver, basearch):
        return 1

    return 0

if __name__ == "__main__":
    sys.exit(main(sys.argv))

